[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_port = /dev/ttyUSB0

; Expose src/ so LVGL finds lv_conf.h
; User_Setup.h is copied into TFT_eSPI lib dir before compile
build_flags =
    -I src

extra_scripts = pre:copy_user_setup.py

lib_deps =
    bodmer/TFT_eSPI
    lvgl/lvgl@^8.3.11
    bblanchon/ArduinoJson@^7.0.0
